### ISSUE TITLE
having problem in building Hops

### ISSUE THREAD

**Issue by aminba90** [logicalclocks/hops-docs#61]
Hi,
When I  try to run " **mvn clean install generate-sources  package -Pdist,ndb,native -Dtar** ", I'm going to face below error. Does anyone has any comments or workaround about how I can fix this?

**[ERROR] Failed to execute goal on project hadoop-main: Could not resolve dependencies for project io.hops:hadoop-main:pom:2.8.2.7-SNAPSHOT: The following artifacts could not be resolved: io.hops.gpu:libhopsnvml:so:2.8.2.7-SNAPSHOT, io.hops.streaming:libhopsyarn:so:2.8.2.7-SNAPSHOT: Could not find artifact io.hops.gpu:libhopsnvml:so:2.8.2.7-SNAPSHOT in hops-snapshot-repository (https://bbc1.sics.se/archiva/repository/Hops/) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project hadoop-main: Could not resolve dependencies for project io.hops:hadoop-main:pom:2.8.2.7-SNAPSHOT: The following artifacts could not be resolved: io.hops.gpu:libhopsnvml:so:2.8.2.7-SNAPSHOT, io.hops.streaming:libhopsyarn:so:2.8.2.7-SNAPSHOT: Could not find artifact io.hops.gpu:libhopsnvml:so:2.8.2.7-SNAPSHOT in hops-snapshot-repository (https://bbc1.sics.se/archiva/repository/Hops/)**

**Comment by tkakantousis** [comment]
@berthoug any ideas?

**Comment by tkakantousis** [comment]
@aminba90 for future issues it's better to post on the hops [repo](https://github.com/hopshadoop/hops)

**Comment by aminba90** [comment]
ok, sure.

**Comment by berthoug** [comment]
Hi,
It looks like there is a part missing in the doc. To run with the ndb profile you need to also build the dependencies needed for the GPU. I will fix the doc, in the meantime you can follow the instructions to build hops in the hops readme: https://github.com/hopshadoop/hops/blob/master/README.md
